version: 2.1

jobs:
  test app:
    docker:
      - image: meteor/circleci:2023.12.1-android-34-node-20
    steps:
      - checkout
      - run:
          name: "Install Meteor"
          command: |
            npx meteor@rc
      - run:
          name: "Run Tests"
          command: |
            cd test-app
            pwd
            ./ci.sh

workflows:
  version: 2
  Blaze Tests:
    jobs:
      - test app
